name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Fixes
    labels:
      - fix
      - bug
      - bugfix
  - title: Maintenance
    labels:
      - chore
      - dependencies
      - github-actions
      - refactor
  - title: Documentation
    labels:
      - docs

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
history-limit: 10
initial-commits-since: "2026-04-27T00:00:00Z"
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - fix
      - bug
      - bugfix
      - chore
      - dependencies
  default: patch
